# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc2c761f54bea5acfece62ba1c6f4f0bb4806125ae7d490e4eb7bf53127ef34190f3dc7a4d512a15f81d1b86bfd44649278916bec38c77ef3e1a4d947d672a6

test:
  secret_key_base: bf447981b4961f48ab35537f277ec7eb59c8da061868ed52d9d19db315dc9d4a808f4f59398766004e389618c5a749cdbe300d241bb490a536a061e7ab0cefcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
